apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: backend
  ports:
    - port: 80
      nodePort: 30080
