apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx:1.19-alpine
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /usr/src/app
            - name: config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: default.conf
